baseURL = "https://rana.li"
languageCode = "en-us"
theme = "hugo-PaperMod"
title = "rana.li"

params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"
